version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: lazyx3/foodgram_backend:latest
    env_file: .env
    volumes:
      - media_volume:/app/media
      - static_volume:/backend_static
    
  frontend:
    image: lazyx3/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: lazyx3/frontend_gateway:latest
    env_file: .env
    volumes:
      - media_volume:/media
      - static_volume:/staticfiles
    ports:
      - 9000:80
    depends_on:
      - frontend